"""Configuration dataclasses for the MerXen pipeline.

All pipeline parameters are defined here as Pydantic models. Configuration
is loaded from JSON files (generated by Nextflow) and validated at startup.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any, Literal

from pydantic import BaseModel, Field, field_validator, model_validator
from pydantic_settings import BaseSettings


class CellposeConfig(BaseModel):
    """Parameters for Cellpose segmentation."""

    model_type: str = "cyto3"
    gpu: bool = True
    diameter: float | None = None
    flow_threshold: float = 0.8
    cellprob_threshold: float = -5.0
    tile_overlap: float = 0.15
    bsize: int = 256
    factor_rescale: float = 1.0

    @field_validator("factor_rescale")
    @classmethod
    def _validate_rescale(cls: type[CellposeConfig], v: float) -> float:
        if abs(v - 1.0) > 1e-12:
            msg = (
                "MerXen is configured for native-resolution tiled Cellpose only. "
                f"Got factor_rescale={v}. Must be 1.0."
            )
            raise ValueError(msg)
        return v


class MaskFilterConfig(BaseModel):
    """Parameters for post-segmentation mask filtering."""

    max_eccentricity: float = 0.99
    min_area_percentile: float = 1.0
    min_area_px: float | None = None
    final_min_area_um2: float | None = 5.0
    final_max_area_um2: float | None = 400.0
    final_filter_chunk_mb: int = 256
    n_jobs: int = 16
    show_progress: bool = True

    @field_validator("final_min_area_um2", "final_max_area_um2")
    @classmethod
    def _validate_optional_area(
        cls: type[MaskFilterConfig],
        v: float | None,
    ) -> float | None:
        if v is not None and v < 0:
            raise ValueError("area thresholds must be non-negative")
        return v

    @field_validator("final_filter_chunk_mb")
    @classmethod
    def _validate_filter_chunk_mb(cls: type[MaskFilterConfig], v: int) -> int:
        if int(v) <= 0:
            raise ValueError("final_filter_chunk_mb must be positive")
        return int(v)

    @model_validator(mode="after")
    def _validate_area_bounds(self: MaskFilterConfig) -> MaskFilterConfig:
        if (
            self.final_min_area_um2 is not None
            and self.final_max_area_um2 is not None
            and self.final_min_area_um2 > self.final_max_area_um2
        ):
            raise ValueError("final_min_area_um2 must be <= final_max_area_um2")
        return self


class TilingConfig(BaseModel):
    """Parameters for memory-adaptive Cellpose tiling."""

    tile_size_candidates: list[int] = [6144, 4096, 3072, 2048]
    tile_overlap: int = 256
    min_tile_size: int = 1024
    status_every_tiles: int = 10
    filter_per_tile: bool = True


class ProsegConfig(BaseModel):
    """Parameters for ProSeg transcript-based segmentation refinement."""

    binary_path: Path = Path("/usr/bin/proseg")
    samples: int = 1200
    voxel_size: float = 0.5
    burnin_voxel_size: float = 1.0
    nuclear_reassignment_prob: float = 0.25
    diffusion_probability: float = 0.25
    cell_compactness: float = 0.04
    expand_initialized_cells: int = 0
    prior_seg_reassignment_prob: float = 0.5
    use_cell_initialization: bool = True
    max_transcript_nucleus_distance: float = 60.0
    diffusion_sigma_far: float | None = None
    num_threads: int = 64
    voxel_layers: int = 2


class MemoryConfig(BaseModel):
    """Memory management parameters."""

    max_system_ram_gb: float = 600.0
    memory_warn_gb: float = 560.0
    memory_check_every_chunks: int = 5
    transcript_chunk_rows: int = 1_000_000
    transcript_status_every_chunks: int = 5


class MerscopeBuildConfig(BaseModel):
    """Options for constructing a MERSCOPE SpatialData object."""

    z_layers: list[int] | None = None
    region_name: str | None = None
    slide_name: str | None = None


class XeniumBuildConfig(BaseModel):
    """Options for constructing a Xenium SpatialData object."""

    cells_boundaries: bool = True
    nucleus_boundaries: bool = True
    cells_as_circles: bool = False
    cells_labels: bool = True
    nucleus_labels: bool = True
    transcripts: bool = True
    morphology_mip: bool = False
    morphology_focus: bool = True
    aligned_images: bool = False
    cells_table: bool = True


class SpatialDataBuildConfig(BaseModel):
    """Configuration for the raw-input to SpatialData build step."""

    dataset_name: str
    platform: Literal["MERSCOPE", "XENIUM"]
    input_path: Path
    output_path: Path
    persistent_output_path: Path | None = None
    merscope_transform_path: Path | None = None
    xenium_spec_path: Path | None = None
    merscope: MerscopeBuildConfig = MerscopeBuildConfig()
    xenium: XeniumBuildConfig = XeniumBuildConfig()


class DatasetConfig(BaseModel):
    """Configuration for a single dataset (one half of a pair)."""

    name: str
    platform: Literal["MERSCOPE", "XENIUM"]
    data_path: Path
    channels: list[str]
    output_dir: Path
    persistent_latest_zarr_path: Path | None = None
    persistent_mask_path: Path | None = None
    persistent_transcripts_path: Path | None = None

    # MERSCOPE-specific
    image_prefix: str | None = None
    z_range: tuple[int, int] | None = None
    transform_path: Path | None = None

    # Xenium-specific
    xenium_spec_path: Path | None = None
    min_qv: float | None = None
    proseg_overrides: dict[str, Any] = Field(default_factory=dict)


class SegmentationConfig(BaseModel):
    """Full configuration for the segmentation step."""

    dataset: DatasetConfig
    cellpose: CellposeConfig = CellposeConfig()
    mask_filter: MaskFilterConfig = MaskFilterConfig()
    tiling: TilingConfig = TilingConfig()
    proseg: ProsegConfig = ProsegConfig()
    memory: MemoryConfig = MemoryConfig()


class EnrichmentConfig(BaseModel):
    """Configuration for the SpatialData enrichment step."""

    dataset_name: str
    platform: Literal["MERSCOPE", "XENIUM"]
    latest_zarr_path: Path
    mask_path: Path
    original_data_path: Path
    output_dir: Path
    persistent_output_path: Path | None = None
    transform_path: Path | None = None


class QCConfig(BaseModel):
    """Configuration for QC metric computation."""

    dataset_name: str
    latest_zarr_path: Path
    output_dir: Path
    table_key: str | None = None
    shape_key: str | None = None


class SpateoAlignmentConfig(BaseModel):
    """Spateo registration parameters for paired-section alignment."""

    model_config = {"populate_by_name": True}

    mode: str = "SN-S"
    device: str = "auto"
    dtype: str = "float32"
    max_iter: int = 360
    nonrigid_start_iter: int = 220
    beta: float = 0.005
    lambda_vf: float = Field(default=3000.0, alias="lambdaVF")
    k: int = Field(default=15, alias="K")
    partial_robust_level: int = 100
    allow_flip: bool = True
    SVI_mode: bool = False
    n_sampling: int = 1_000
    sparse_top_k: int = 512
    sparse_calculation_mode: bool = True
    use_chunk: bool = True
    chunk_capacity: int = 1
    normalize_total: float = 10_000.0
    log1p: bool = True
    use_hvg: bool = False
    n_top_genes: int = 100
    use_pca: bool = True
    n_pcs: int = 50
    max_alignment_cells: int | None = 35_000
    alignment_seed: int = 21
    include_image_features: bool = True
    selected_mode: Literal["rigid", "nonrigid"] = "nonrigid"
    rbf_neighbors: int = 64
    rbf_smoothing: float = 0.0
    max_nonrigid_anchors: int = 5_000
    tune: bool = False
    param_grid: list[dict[str, Any]] = Field(default_factory=list)


class AlignmentConfig(BaseModel):
    """Configuration for paired MERSCOPE-to-Xenium section alignment."""

    pair_id: str
    merscope_zarr_path: Path
    xenium_zarr_path: Path
    output_dir: Path
    fixed_platform: Literal["XENIUM"] = "XENIUM"
    moving_platform: Literal["MERSCOPE"] = "MERSCOPE"
    write_aligned_zarrs: bool = True
    spateo: SpateoAlignmentConfig = SpateoAlignmentConfig()


class AlignmentQCConfig(BaseModel):
    """Configuration for post-alignment QC metrics."""

    pair_id: str
    merscope_zarr_path: Path
    xenium_zarr_path: Path
    output_dir: Path
    transform_json_path: Path | None = None
    grid_rows: int = 10
    grid_cols: int = 10


class ComparisonConfig(BaseModel):
    """Configuration for cross-platform comparison."""

    merscope_zarr_path: Path
    xenium_zarr_path: Path
    output_dir: Path
    pair_id: str
    merscope_table_key: str | None = None
    xenium_table_key: str | None = None


class VisualizationSampleConfig(BaseModel):
    """One SpatialData sample to include in visualization output."""

    sample_id: str
    platform: Literal["MERSCOPE", "XENIUM"]
    zarr_path: Path
    segmentation: str | None = None
    table_key: str | None = None
    shape_key: str | None = None


class VisualizationConfig(BaseModel):
    """Configuration for generating plots."""

    output_dir: Path
    pair_id: str
    samples: list[VisualizationSampleConfig] = Field(default_factory=list)
    merscope_zarr_path: Path | None = None
    xenium_zarr_path: Path | None = None

    @model_validator(mode="after")
    def _populate_legacy_samples(self: VisualizationConfig) -> VisualizationConfig:
        if not self.samples:
            legacy_samples = []
            if self.merscope_zarr_path is not None:
                legacy_samples.append(
                    VisualizationSampleConfig(
                        sample_id=f"{self.pair_id}_MERSCOPE",
                        platform="MERSCOPE",
                        zarr_path=self.merscope_zarr_path,
                    )
                )
            if self.xenium_zarr_path is not None:
                legacy_samples.append(
                    VisualizationSampleConfig(
                        sample_id=f"{self.pair_id}_XENIUM",
                        platform="XENIUM",
                        zarr_path=self.xenium_zarr_path,
                    )
                )
            self.samples = legacy_samples

        if not self.samples:
            raise ValueError(
                "VisualizationConfig requires at least one sample or legacy "
                "merscope_zarr_path/xenium_zarr_path values."
            )

        seen_platforms: set[str] = set()
        for sample in self.samples:
            if sample.platform in seen_platforms:
                raise ValueError(
                    f"VisualizationConfig has duplicate platform {sample.platform!r}"
                )
            seen_platforms.add(sample.platform)

        return self


class ClusteringSquidpySampleConfig(BaseModel):
    """One SpatialData sample to cluster with Scanpy/Squidpy."""

    sample_id: str
    platform: Literal["MERSCOPE", "XENIUM"]
    zarr_path: Path
    segmentation: str | None = None
    table_key: str | None = None
    shape_key: str | None = None


class ClusteringSquidpyRoundConfig(BaseModel):
    """Per-round Scanpy/Squidpy clustering overrides.

    ``None`` values inherit the top-level ``ClusteringSquidpyConfig`` setting.
    Round-specific defaults set only the intended Leiden granularity.
    """

    min_counts: int | None = Field(default=None, ge=0)
    min_cells: int | None = Field(default=None, ge=1)
    n_pcs: int | None = Field(default=None, ge=1)
    n_neighbors: int | None = Field(default=None, ge=2)
    leiden_resolution: float = Field(default=0.5, gt=0.0)
    umap_min_dist: float | None = Field(default=None, ge=0.0)
    umap_spread: float | None = Field(default=None, gt=0.0)


class ClusteringSquidpyAnnotationConfig(BaseModel):
    """Atlas marker options for hierarchical broad-cluster annotation."""

    marker_lookup_path: Path | None = Path(
        "/media/mathieubo/SSD2/MerXen/mapmycells/query_markers.n10.20240221800.json"
    )
    taxonomy_metadata_path: Path | None = Path(
        "/media/mathieubo/SSD2/MerXen/mapmycells/abc_whb/metadata/"
        "WHB-taxonomy/20240330/cluster_annotation_term.csv"
    )
    cluster_membership_path: Path | None = Path(
        "/media/mathieubo/SSD2/MerXen/mapmycells/abc_whb/metadata/"
        "WHB-taxonomy/20240330/cluster_to_cluster_annotation_membership.csv"
    )
    reference_cache_dir: Path | None = Path("/media/mathieubo/SSD2/MerXen/mapmycells")
    reference_gene_metadata_paths: list[Path] = Field(default_factory=list)
    marker_level: str = "CCN202210140_SUPC"
    min_marker_overlap: int = Field(default=3, ge=1)
    max_markers_per_label: int | None = Field(default=80, ge=1)
    score_margin_threshold: float = Field(default=0.0, ge=0.0)
    unknown_label: str = "Mixed/Unknown"


class ClusteringSquidpyConfig(BaseModel):
    """Configuration for the Squidpy/Scanpy clustering stage."""

    pair_id: str
    output_dir: Path
    samples: list[ClusteringSquidpySampleConfig]
    drop_control_features: bool = True
    min_counts: int = 10
    min_cells: int = 5
    normalize_target_sum: float | None = None
    normalize_exclude_highly_expressed: bool = False
    normalize_max_fraction: float = 0.05
    n_pcs: int = 60
    n_neighbors: int = 30
    leiden_resolution: float = 0.5
    umap_min_dist: float = 0.3
    umap_spread: float = 1.0
    random_seed: int = 0
    spatial_point_size: float = 0.5
    spatial_scatter_point_size: float = 2.0
    figure_dpi: int = 180
    use_gpu: bool = True
    hierarchical_enabled: bool = True
    broad_round: ClusteringSquidpyRoundConfig = Field(
        default_factory=lambda: ClusteringSquidpyRoundConfig(leiden_resolution=0.2)
    )
    subcluster_round: ClusteringSquidpyRoundConfig = Field(
        default_factory=lambda: ClusteringSquidpyRoundConfig(leiden_resolution=0.5)
    )
    subcluster_resolution_overrides: dict[str, float] = Field(default_factory=dict)
    neuron_split_round: ClusteringSquidpyRoundConfig = Field(
        default_factory=lambda: ClusteringSquidpyRoundConfig(leiden_resolution=0.15)
    )
    neuron_subcluster_round: ClusteringSquidpyRoundConfig = Field(
        default_factory=lambda: ClusteringSquidpyRoundConfig(leiden_resolution=0.5)
    )
    broad_annotation: ClusteringSquidpyAnnotationConfig = Field(
        default_factory=ClusteringSquidpyAnnotationConfig
    )
    min_branch_cells: int = Field(default=50, ge=1)


class MapMyCellsSampleConfig(BaseModel):
    """One clustered AnnData sample to annotate with MapMyCells."""

    sample_id: str
    platform: Literal["MERSCOPE", "XENIUM"]
    anndata_path: Path
    query_layer: str | None = "counts"
    gene_id_column: str | None = None
    obs_id_column: str | None = None


class MapMyCellsConfig(BaseModel):
    """Configuration for local MapMyCells cell type assignment."""

    pair_id: str
    output_dir: Path
    samples: list[MapMyCellsSampleConfig]
    reference_mode: Literal["whole_brain", "region", "both"] = "both"
    marker_lookup_path: Path | None = None
    precomputed_stats_path: Path | None = None
    region_name: str = "frontal_a44_a45_a46_a32_acc"
    region_labels: list[str] = Field(
        default_factory=lambda: [
            "Human A44-A45",
            "Human A46",
            "Human A32",
            "Human ACC",
        ]
    )
    region_cache_dir: Path = Path("/media/mathieubo/SSD2/MerXen/mapmycells")
    region_min_cells_per_leaf: int = Field(default=10, ge=1)
    region_force_rebuild: bool = False
    region_query_markers_n_per_utility: int = Field(default=10, ge=1)
    drop_level: str | None = None
    normalization: Literal["raw", "log2CPM"] = "raw"
    bootstrap_factor: float = Field(default=0.9, gt=0.0, le=1.0)
    bootstrap_iteration: int = Field(default=100, ge=1)
    n_processors: int = Field(default=4, ge=1)
    chunk_size: int | None = Field(default=None, ge=1)
    rng_seed: int | None = None
    max_gb: float | None = Field(default=None, gt=0.0)
    tmp_dir: Path | None = None
    cloud_safe: bool = False
    flatten: bool = False
    verbose_csv: bool = False
    plots_only: bool = False
    extra_args: list[str] = Field(default_factory=list)

    @field_validator("region_labels", mode="before")
    @classmethod
    def _parse_region_labels(cls: type[MapMyCellsConfig], value: Any) -> list[str]:
        if value is None:
            return []
        if isinstance(value, str):
            raw = value.strip()
            if not raw:
                return []
            if raw.startswith("["):
                import json

                parsed = json.loads(raw)
                if not isinstance(parsed, list):
                    raise ValueError("region_labels JSON must decode to a list")
                value = parsed
            else:
                return [part.strip() for part in raw.split(",") if part.strip()]
        if isinstance(value, list | tuple | set):
            return [str(item).strip() for item in value if str(item).strip()]
        raise ValueError("region_labels must be a list or comma-separated string")

    @field_validator("region_name")
    @classmethod
    def _validate_region_name(cls: type[MapMyCellsConfig], value: str) -> str:
        cleaned = value.strip()
        if not cleaned:
            raise ValueError("region_name must not be empty")
        return cleaned

    @model_validator(mode="after")
    def _validate_reference_inputs(self: MapMyCellsConfig) -> MapMyCellsConfig:
        if not self.plots_only and self.reference_mode in {"whole_brain", "both"}:
            if self.marker_lookup_path is None:
                raise ValueError(
                    "marker_lookup_path is required when reference_mode includes "
                    "whole_brain"
                )
            if self.precomputed_stats_path is None:
                raise ValueError(
                    "precomputed_stats_path is required when reference_mode includes "
                    "whole_brain"
                )
        if (
            not self.plots_only
            and self.reference_mode in {"region", "both"}
            and not self.region_labels
        ):
            raise ValueError(
                "region_labels must contain at least one Allen WHB ROI label when "
                "reference_mode includes region"
            )
        return self


class PipelineConfig(BaseSettings):
    """Top-level pipeline configuration, loadable from env vars."""

    output_root: Path = Path("./results")
    proseg_search_paths: list[Path] = [
        Path("/usr/bin/proseg"),
        Path("/usr/local/bin/proseg"),
    ]
    proseg_install_path: Path = Path("/usr/bin/proseg")
    proseg_auto_install: bool = True
    max_ram_gb: float = 600.0

    model_config = {"env_prefix": "MERXEN_"}


def load_config_from_json(path: Path, config_class: type[BaseModel]) -> BaseModel:
    """Load and validate a config from a JSON file.

    Args:
        path: Path to the JSON config file.
        config_class: The Pydantic model class to validate against.

    Returns:
        A validated config instance.
    """
    import json

    with open(path) as f:
        data = json.load(f)
    return config_class.model_validate(data)
