"""Configuration dataclasses for the MerXen pipeline.

All pipeline parameters are defined here as Pydantic models. Configuration
is loaded from JSON files (generated by Nextflow) and validated at startup.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any, Literal

from pydantic import BaseModel, Field, field_validator
from pydantic_settings import BaseSettings


class CellposeConfig(BaseModel):
    """Parameters for Cellpose segmentation."""

    model_type: str = "cyto3"
    gpu: bool = True
    diameter: float | None = None
    flow_threshold: float = 0.8
    cellprob_threshold: float = -5.0
    tile_overlap: float = 0.15
    bsize: int = 256
    factor_rescale: float = 1.0

    @field_validator("factor_rescale")
    @classmethod
    def _validate_rescale(cls: type[CellposeConfig], v: float) -> float:
        if abs(v - 1.0) > 1e-12:
            msg = (
                "MerXen is configured for native-resolution tiled Cellpose only. "
                f"Got factor_rescale={v}. Must be 1.0."
            )
            raise ValueError(msg)
        return v


class MaskFilterConfig(BaseModel):
    """Parameters for post-segmentation mask filtering."""

    max_eccentricity: float = 0.99
    min_area_percentile: float = 1.0
    min_area_px: float | None = None
    n_jobs: int = 16
    show_progress: bool = True


class TilingConfig(BaseModel):
    """Parameters for memory-adaptive Cellpose tiling."""

    tile_size_candidates: list[int] = [6144, 4096, 3072, 2048]
    tile_overlap: int = 256
    min_tile_size: int = 1024
    status_every_tiles: int = 10
    filter_per_tile: bool = True


class ProsegConfig(BaseModel):
    """Parameters for ProSeg transcript-based segmentation refinement."""

    binary_path: Path = Path("/usr/local/bin/proseg")
    samples: int = 1200
    voxel_size: float = 0.5
    burnin_voxel_size: float = 1.0
    nuclear_reassignment_prob: float = 0.25
    diffusion_probability: float = 0.25
    cell_compactness: float = 0.04
    expand_initialized_cells: int = 0
    prior_seg_reassignment_prob: float = 0.5
    use_cell_initialization: bool = True
    max_transcript_nucleus_distance: float = 60.0
    diffusion_sigma_far: float | None = None
    num_threads: int = 64
    voxel_layers: int = 2


class MemoryConfig(BaseModel):
    """Memory management parameters."""

    max_system_ram_gb: float = 600.0
    memory_warn_gb: float = 560.0
    memory_check_every_chunks: int = 5
    transcript_chunk_rows: int = 1_000_000
    transcript_status_every_chunks: int = 5


class MerscopeBuildConfig(BaseModel):
    """Options for constructing a MERSCOPE SpatialData object."""

    z_layers: list[int] | None = None
    region_name: str | None = None
    slide_name: str | None = None


class XeniumBuildConfig(BaseModel):
    """Options for constructing a Xenium SpatialData object."""

    cells_boundaries: bool = True
    nucleus_boundaries: bool = True
    cells_as_circles: bool = False
    cells_labels: bool = True
    nucleus_labels: bool = True
    transcripts: bool = True
    morphology_mip: bool = False
    morphology_focus: bool = True
    aligned_images: bool = False
    cells_table: bool = True


class SpatialDataBuildConfig(BaseModel):
    """Configuration for the raw-input to SpatialData build step."""

    dataset_name: str
    platform: Literal["MERSCOPE", "XENIUM"]
    input_path: Path
    output_path: Path
    persistent_output_path: Path | None = None
    merscope_transform_path: Path | None = None
    xenium_spec_path: Path | None = None
    merscope: MerscopeBuildConfig = MerscopeBuildConfig()
    xenium: XeniumBuildConfig = XeniumBuildConfig()


class DatasetConfig(BaseModel):
    """Configuration for a single dataset (one half of a pair)."""

    name: str
    platform: Literal["MERSCOPE", "XENIUM"]
    data_path: Path
    channels: list[str]
    output_dir: Path
    persistent_latest_zarr_path: Path | None = None
    persistent_mask_path: Path | None = None
    persistent_transcripts_path: Path | None = None

    # MERSCOPE-specific
    image_prefix: str | None = None
    z_range: tuple[int, int] | None = None
    transform_path: Path | None = None

    # Xenium-specific
    xenium_spec_path: Path | None = None
    min_qv: float | None = None
    proseg_overrides: dict[str, Any] = Field(default_factory=dict)


class SegmentationConfig(BaseModel):
    """Full configuration for the segmentation step."""

    dataset: DatasetConfig
    cellpose: CellposeConfig = CellposeConfig()
    mask_filter: MaskFilterConfig = MaskFilterConfig()
    tiling: TilingConfig = TilingConfig()
    proseg: ProsegConfig = ProsegConfig()
    memory: MemoryConfig = MemoryConfig()


class EnrichmentConfig(BaseModel):
    """Configuration for the SpatialData enrichment step."""

    dataset_name: str
    platform: Literal["MERSCOPE", "XENIUM"]
    latest_zarr_path: Path
    mask_path: Path
    original_data_path: Path
    output_dir: Path
    persistent_output_path: Path | None = None
    transform_path: Path | None = None


class QCConfig(BaseModel):
    """Configuration for QC metric computation."""

    dataset_name: str
    latest_zarr_path: Path
    output_dir: Path


class SpateoAlignmentConfig(BaseModel):
    """Spateo registration parameters for paired-section alignment."""

    model_config = {"populate_by_name": True}

    mode: str = "SN-S"
    device: str = "auto"
    dtype: str = "float32"
    max_iter: int = 360
    nonrigid_start_iter: int = 220
    beta: float = 0.005
    lambda_vf: float = Field(default=3000.0, alias="lambdaVF")
    k: int = Field(default=15, alias="K")
    partial_robust_level: int = 100
    allow_flip: bool = True
    SVI_mode: bool = False
    n_sampling: int = 1_000
    sparse_top_k: int = 512
    sparse_calculation_mode: bool = True
    use_chunk: bool = True
    chunk_capacity: int = 1
    normalize_total: float = 10_000.0
    log1p: bool = True
    use_hvg: bool = False
    n_top_genes: int = 100
    use_pca: bool = True
    n_pcs: int = 50
    max_alignment_cells: int | None = 35_000
    alignment_seed: int = 21
    include_image_features: bool = True
    selected_mode: Literal["rigid", "nonrigid"] = "nonrigid"
    rbf_neighbors: int = 64
    rbf_smoothing: float = 0.0
    max_nonrigid_anchors: int = 5_000
    tune: bool = False
    param_grid: list[dict[str, Any]] = Field(default_factory=list)


class AlignmentConfig(BaseModel):
    """Configuration for paired MERSCOPE-to-Xenium section alignment."""

    pair_id: str
    merscope_zarr_path: Path
    xenium_zarr_path: Path
    output_dir: Path
    fixed_platform: Literal["XENIUM"] = "XENIUM"
    moving_platform: Literal["MERSCOPE"] = "MERSCOPE"
    write_aligned_zarrs: bool = True
    spateo: SpateoAlignmentConfig = SpateoAlignmentConfig()


class AlignmentQCConfig(BaseModel):
    """Configuration for post-alignment QC metrics."""

    pair_id: str
    merscope_zarr_path: Path
    xenium_zarr_path: Path
    output_dir: Path
    transform_json_path: Path | None = None
    grid_rows: int = 10
    grid_cols: int = 10


class ComparisonConfig(BaseModel):
    """Configuration for cross-platform comparison."""

    merscope_zarr_path: Path
    xenium_zarr_path: Path
    output_dir: Path
    pair_id: str


class VisualizationConfig(BaseModel):
    """Configuration for generating plots."""

    merscope_zarr_path: Path
    xenium_zarr_path: Path
    output_dir: Path
    pair_id: str


class ClusteringSquidpySampleConfig(BaseModel):
    """One SpatialData sample to cluster with Scanpy/Squidpy."""

    sample_id: str
    platform: Literal["MERSCOPE", "XENIUM"]
    zarr_path: Path
    table_key: str | None = None
    shape_key: str | None = None


class ClusteringSquidpyConfig(BaseModel):
    """Configuration for the Squidpy/Scanpy clustering stage."""

    pair_id: str
    output_dir: Path
    samples: list[ClusteringSquidpySampleConfig]
    min_counts: int = 10
    min_cells: int = 5
    normalize_target_sum: float | None = None
    n_pcs: int = 50
    n_neighbors: int = 15
    leiden_resolution: float = 1.0
    random_seed: int = 0
    spatial_point_size: float = 2.0
    figure_dpi: int = 160


class PipelineConfig(BaseSettings):
    """Top-level pipeline configuration, loadable from env vars."""

    output_root: Path = Path("./results")
    proseg_binary: Path = Path("/usr/local/bin/proseg")
    max_ram_gb: float = 600.0

    model_config = {"env_prefix": "MERXEN_"}


def load_config_from_json(path: Path, config_class: type[BaseModel]) -> BaseModel:
    """Load and validate a config from a JSON file.

    Args:
        path: Path to the JSON config file.
        config_class: The Pydantic model class to validate against.

    Returns:
        A validated config instance.
    """
    import json

    with open(path) as f:
        data = json.load(f)
    return config_class.model_validate(data)
